// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvgheryvhzbfjqonergo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2Z2hlcnl2aHpiZmpxb25lcmdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NTM5NzEsImV4cCI6MjA1MzAyOTk3MX0.QwmsDAJQOOK8R_Hn-b_RCUEilwhXL02dQn4XpATRDkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);