
version: '3.8'

services:
  cmi-payment:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - CMI_MERCHANT_ID=${CMI_MERCHANT_ID}
      - CMI_ENDPOINT=${CMI_ENDPOINT}
    volumes:
      - .:/app
